# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.13

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /FireGUARD/FireSTARR

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /FireGUARD/FireSTARR

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /FireGUARD/FireSTARR/CMakeFiles /FireGUARD/FireSTARR/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /FireGUARD/FireSTARR/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named FireSTARR

# Build rule for target.
FireSTARR: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 FireSTARR
.PHONY : FireSTARR

# fast build rule for target.
FireSTARR/fast:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/build
.PHONY : FireSTARR/fast

src/Database.o: src/Database.cpp.o

.PHONY : src/Database.o

# target to build an object file
src/Database.cpp.o:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Database.cpp.o
.PHONY : src/Database.cpp.o

src/Database.i: src/Database.cpp.i

.PHONY : src/Database.i

# target to preprocess a source file
src/Database.cpp.i:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Database.cpp.i
.PHONY : src/Database.cpp.i

src/Database.s: src/Database.cpp.s

.PHONY : src/Database.s

# target to generate assembly for a file
src/Database.cpp.s:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Database.cpp.s
.PHONY : src/Database.cpp.s

src/Duff.o: src/Duff.cpp.o

.PHONY : src/Duff.o

# target to build an object file
src/Duff.cpp.o:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Duff.cpp.o
.PHONY : src/Duff.cpp.o

src/Duff.i: src/Duff.cpp.i

.PHONY : src/Duff.i

# target to preprocess a source file
src/Duff.cpp.i:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Duff.cpp.i
.PHONY : src/Duff.cpp.i

src/Duff.s: src/Duff.cpp.s

.PHONY : src/Duff.s

# target to generate assembly for a file
src/Duff.cpp.s:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Duff.cpp.s
.PHONY : src/Duff.cpp.s

src/Environment.o: src/Environment.cpp.o

.PHONY : src/Environment.o

# target to build an object file
src/Environment.cpp.o:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Environment.cpp.o
.PHONY : src/Environment.cpp.o

src/Environment.i: src/Environment.cpp.i

.PHONY : src/Environment.i

# target to preprocess a source file
src/Environment.cpp.i:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Environment.cpp.i
.PHONY : src/Environment.cpp.i

src/Environment.s: src/Environment.cpp.s

.PHONY : src/Environment.s

# target to generate assembly for a file
src/Environment.cpp.s:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Environment.cpp.s
.PHONY : src/Environment.cpp.s

src/EnvironmentInfo.o: src/EnvironmentInfo.cpp.o

.PHONY : src/EnvironmentInfo.o

# target to build an object file
src/EnvironmentInfo.cpp.o:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/EnvironmentInfo.cpp.o
.PHONY : src/EnvironmentInfo.cpp.o

src/EnvironmentInfo.i: src/EnvironmentInfo.cpp.i

.PHONY : src/EnvironmentInfo.i

# target to preprocess a source file
src/EnvironmentInfo.cpp.i:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/EnvironmentInfo.cpp.i
.PHONY : src/EnvironmentInfo.cpp.i

src/EnvironmentInfo.s: src/EnvironmentInfo.cpp.s

.PHONY : src/EnvironmentInfo.s

# target to generate assembly for a file
src/EnvironmentInfo.cpp.s:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/EnvironmentInfo.cpp.s
.PHONY : src/EnvironmentInfo.cpp.s

src/FBP45.o: src/FBP45.cpp.o

.PHONY : src/FBP45.o

# target to build an object file
src/FBP45.cpp.o:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/FBP45.cpp.o
.PHONY : src/FBP45.cpp.o

src/FBP45.i: src/FBP45.cpp.i

.PHONY : src/FBP45.i

# target to preprocess a source file
src/FBP45.cpp.i:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/FBP45.cpp.i
.PHONY : src/FBP45.cpp.i

src/FBP45.s: src/FBP45.cpp.s

.PHONY : src/FBP45.s

# target to generate assembly for a file
src/FBP45.cpp.s:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/FBP45.cpp.s
.PHONY : src/FBP45.cpp.s

src/FWI.o: src/FWI.cpp.o

.PHONY : src/FWI.o

# target to build an object file
src/FWI.cpp.o:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/FWI.cpp.o
.PHONY : src/FWI.cpp.o

src/FWI.i: src/FWI.cpp.i

.PHONY : src/FWI.i

# target to preprocess a source file
src/FWI.cpp.i:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/FWI.cpp.i
.PHONY : src/FWI.cpp.i

src/FWI.s: src/FWI.cpp.s

.PHONY : src/FWI.s

# target to generate assembly for a file
src/FWI.cpp.s:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/FWI.cpp.s
.PHONY : src/FWI.cpp.s

src/FireSpread.o: src/FireSpread.cpp.o

.PHONY : src/FireSpread.o

# target to build an object file
src/FireSpread.cpp.o:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/FireSpread.cpp.o
.PHONY : src/FireSpread.cpp.o

src/FireSpread.i: src/FireSpread.cpp.i

.PHONY : src/FireSpread.i

# target to preprocess a source file
src/FireSpread.cpp.i:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/FireSpread.cpp.i
.PHONY : src/FireSpread.cpp.i

src/FireSpread.s: src/FireSpread.cpp.s

.PHONY : src/FireSpread.s

# target to generate assembly for a file
src/FireSpread.cpp.s:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/FireSpread.cpp.s
.PHONY : src/FireSpread.cpp.s

src/FireWeather.o: src/FireWeather.cpp.o

.PHONY : src/FireWeather.o

# target to build an object file
src/FireWeather.cpp.o:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/FireWeather.cpp.o
.PHONY : src/FireWeather.cpp.o

src/FireWeather.i: src/FireWeather.cpp.i

.PHONY : src/FireWeather.i

# target to preprocess a source file
src/FireWeather.cpp.i:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/FireWeather.cpp.i
.PHONY : src/FireWeather.cpp.i

src/FireWeather.s: src/FireWeather.cpp.s

.PHONY : src/FireWeather.s

# target to generate assembly for a file
src/FireWeather.cpp.s:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/FireWeather.cpp.s
.PHONY : src/FireWeather.cpp.s

src/FuelLookup.o: src/FuelLookup.cpp.o

.PHONY : src/FuelLookup.o

# target to build an object file
src/FuelLookup.cpp.o:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/FuelLookup.cpp.o
.PHONY : src/FuelLookup.cpp.o

src/FuelLookup.i: src/FuelLookup.cpp.i

.PHONY : src/FuelLookup.i

# target to preprocess a source file
src/FuelLookup.cpp.i:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/FuelLookup.cpp.i
.PHONY : src/FuelLookup.cpp.i

src/FuelLookup.s: src/FuelLookup.cpp.s

.PHONY : src/FuelLookup.s

# target to generate assembly for a file
src/FuelLookup.cpp.s:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/FuelLookup.cpp.s
.PHONY : src/FuelLookup.cpp.s

src/FuelType.o: src/FuelType.cpp.o

.PHONY : src/FuelType.o

# target to build an object file
src/FuelType.cpp.o:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/FuelType.cpp.o
.PHONY : src/FuelType.cpp.o

src/FuelType.i: src/FuelType.cpp.i

.PHONY : src/FuelType.i

# target to preprocess a source file
src/FuelType.cpp.i:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/FuelType.cpp.i
.PHONY : src/FuelType.cpp.i

src/FuelType.s: src/FuelType.cpp.s

.PHONY : src/FuelType.s

# target to generate assembly for a file
src/FuelType.cpp.s:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/FuelType.cpp.s
.PHONY : src/FuelType.cpp.s

src/FwiStream.o: src/FwiStream.cpp.o

.PHONY : src/FwiStream.o

# target to build an object file
src/FwiStream.cpp.o:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/FwiStream.cpp.o
.PHONY : src/FwiStream.cpp.o

src/FwiStream.i: src/FwiStream.cpp.i

.PHONY : src/FwiStream.i

# target to preprocess a source file
src/FwiStream.cpp.i:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/FwiStream.cpp.i
.PHONY : src/FwiStream.cpp.i

src/FwiStream.s: src/FwiStream.cpp.s

.PHONY : src/FwiStream.s

# target to generate assembly for a file
src/FwiStream.cpp.s:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/FwiStream.cpp.s
.PHONY : src/FwiStream.cpp.s

src/Grid.o: src/Grid.cpp.o

.PHONY : src/Grid.o

# target to build an object file
src/Grid.cpp.o:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Grid.cpp.o
.PHONY : src/Grid.cpp.o

src/Grid.i: src/Grid.cpp.i

.PHONY : src/Grid.i

# target to preprocess a source file
src/Grid.cpp.i:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Grid.cpp.i
.PHONY : src/Grid.cpp.i

src/Grid.s: src/Grid.cpp.s

.PHONY : src/Grid.s

# target to generate assembly for a file
src/Grid.cpp.s:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Grid.cpp.s
.PHONY : src/Grid.cpp.s

src/IntensityMap.o: src/IntensityMap.cpp.o

.PHONY : src/IntensityMap.o

# target to build an object file
src/IntensityMap.cpp.o:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/IntensityMap.cpp.o
.PHONY : src/IntensityMap.cpp.o

src/IntensityMap.i: src/IntensityMap.cpp.i

.PHONY : src/IntensityMap.i

# target to preprocess a source file
src/IntensityMap.cpp.i:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/IntensityMap.cpp.i
.PHONY : src/IntensityMap.cpp.i

src/IntensityMap.s: src/IntensityMap.cpp.s

.PHONY : src/IntensityMap.s

# target to generate assembly for a file
src/IntensityMap.cpp.s:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/IntensityMap.cpp.s
.PHONY : src/IntensityMap.cpp.s

src/Iteration.o: src/Iteration.cpp.o

.PHONY : src/Iteration.o

# target to build an object file
src/Iteration.cpp.o:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Iteration.cpp.o
.PHONY : src/Iteration.cpp.o

src/Iteration.i: src/Iteration.cpp.i

.PHONY : src/Iteration.i

# target to preprocess a source file
src/Iteration.cpp.i:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Iteration.cpp.i
.PHONY : src/Iteration.cpp.i

src/Iteration.s: src/Iteration.cpp.s

.PHONY : src/Iteration.s

# target to generate assembly for a file
src/Iteration.cpp.s:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Iteration.cpp.s
.PHONY : src/Iteration.cpp.s

src/Log.o: src/Log.cpp.o

.PHONY : src/Log.o

# target to build an object file
src/Log.cpp.o:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Log.cpp.o
.PHONY : src/Log.cpp.o

src/Log.i: src/Log.cpp.i

.PHONY : src/Log.i

# target to preprocess a source file
src/Log.cpp.i:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Log.cpp.i
.PHONY : src/Log.cpp.i

src/Log.s: src/Log.cpp.s

.PHONY : src/Log.s

# target to generate assembly for a file
src/Log.cpp.s:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Log.cpp.s
.PHONY : src/Log.cpp.s

src/Main.o: src/Main.cpp.o

.PHONY : src/Main.o

# target to build an object file
src/Main.cpp.o:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Main.cpp.o
.PHONY : src/Main.cpp.o

src/Main.i: src/Main.cpp.i

.PHONY : src/Main.i

# target to preprocess a source file
src/Main.cpp.i:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Main.cpp.i
.PHONY : src/Main.cpp.i

src/Main.s: src/Main.cpp.s

.PHONY : src/Main.s

# target to generate assembly for a file
src/Main.cpp.s:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Main.cpp.s
.PHONY : src/Main.cpp.s

src/Model.o: src/Model.cpp.o

.PHONY : src/Model.o

# target to build an object file
src/Model.cpp.o:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Model.cpp.o
.PHONY : src/Model.cpp.o

src/Model.i: src/Model.cpp.i

.PHONY : src/Model.i

# target to preprocess a source file
src/Model.cpp.i:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Model.cpp.i
.PHONY : src/Model.cpp.i

src/Model.s: src/Model.cpp.s

.PHONY : src/Model.s

# target to generate assembly for a file
src/Model.cpp.s:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Model.cpp.s
.PHONY : src/Model.cpp.s

src/Observer.o: src/Observer.cpp.o

.PHONY : src/Observer.o

# target to build an object file
src/Observer.cpp.o:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Observer.cpp.o
.PHONY : src/Observer.cpp.o

src/Observer.i: src/Observer.cpp.i

.PHONY : src/Observer.i

# target to preprocess a source file
src/Observer.cpp.i:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Observer.cpp.i
.PHONY : src/Observer.cpp.i

src/Observer.s: src/Observer.cpp.s

.PHONY : src/Observer.s

# target to generate assembly for a file
src/Observer.cpp.s:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Observer.cpp.s
.PHONY : src/Observer.cpp.s

src/Perimeter.o: src/Perimeter.cpp.o

.PHONY : src/Perimeter.o

# target to build an object file
src/Perimeter.cpp.o:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Perimeter.cpp.o
.PHONY : src/Perimeter.cpp.o

src/Perimeter.i: src/Perimeter.cpp.i

.PHONY : src/Perimeter.i

# target to preprocess a source file
src/Perimeter.cpp.i:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Perimeter.cpp.i
.PHONY : src/Perimeter.cpp.i

src/Perimeter.s: src/Perimeter.cpp.s

.PHONY : src/Perimeter.s

# target to generate assembly for a file
src/Perimeter.cpp.s:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Perimeter.cpp.s
.PHONY : src/Perimeter.cpp.s

src/ProbabilityMap.o: src/ProbabilityMap.cpp.o

.PHONY : src/ProbabilityMap.o

# target to build an object file
src/ProbabilityMap.cpp.o:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/ProbabilityMap.cpp.o
.PHONY : src/ProbabilityMap.cpp.o

src/ProbabilityMap.i: src/ProbabilityMap.cpp.i

.PHONY : src/ProbabilityMap.i

# target to preprocess a source file
src/ProbabilityMap.cpp.i:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/ProbabilityMap.cpp.i
.PHONY : src/ProbabilityMap.cpp.i

src/ProbabilityMap.s: src/ProbabilityMap.cpp.s

.PHONY : src/ProbabilityMap.s

# target to generate assembly for a file
src/ProbabilityMap.cpp.s:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/ProbabilityMap.cpp.s
.PHONY : src/ProbabilityMap.cpp.s

src/SafeVector.o: src/SafeVector.cpp.o

.PHONY : src/SafeVector.o

# target to build an object file
src/SafeVector.cpp.o:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/SafeVector.cpp.o
.PHONY : src/SafeVector.cpp.o

src/SafeVector.i: src/SafeVector.cpp.i

.PHONY : src/SafeVector.i

# target to preprocess a source file
src/SafeVector.cpp.i:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/SafeVector.cpp.i
.PHONY : src/SafeVector.cpp.i

src/SafeVector.s: src/SafeVector.cpp.s

.PHONY : src/SafeVector.s

# target to generate assembly for a file
src/SafeVector.cpp.s:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/SafeVector.cpp.s
.PHONY : src/SafeVector.cpp.s

src/Scenario.o: src/Scenario.cpp.o

.PHONY : src/Scenario.o

# target to build an object file
src/Scenario.cpp.o:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Scenario.cpp.o
.PHONY : src/Scenario.cpp.o

src/Scenario.i: src/Scenario.cpp.i

.PHONY : src/Scenario.i

# target to preprocess a source file
src/Scenario.cpp.i:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Scenario.cpp.i
.PHONY : src/Scenario.cpp.i

src/Scenario.s: src/Scenario.cpp.s

.PHONY : src/Scenario.s

# target to generate assembly for a file
src/Scenario.cpp.s:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Scenario.cpp.s
.PHONY : src/Scenario.cpp.s

src/Settings.o: src/Settings.cpp.o

.PHONY : src/Settings.o

# target to build an object file
src/Settings.cpp.o:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Settings.cpp.o
.PHONY : src/Settings.cpp.o

src/Settings.i: src/Settings.cpp.i

.PHONY : src/Settings.i

# target to preprocess a source file
src/Settings.cpp.i:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Settings.cpp.i
.PHONY : src/Settings.cpp.i

src/Settings.s: src/Settings.cpp.s

.PHONY : src/Settings.s

# target to generate assembly for a file
src/Settings.cpp.s:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Settings.cpp.s
.PHONY : src/Settings.cpp.s

src/StandardFuel.o: src/StandardFuel.cpp.o

.PHONY : src/StandardFuel.o

# target to build an object file
src/StandardFuel.cpp.o:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/StandardFuel.cpp.o
.PHONY : src/StandardFuel.cpp.o

src/StandardFuel.i: src/StandardFuel.cpp.i

.PHONY : src/StandardFuel.i

# target to preprocess a source file
src/StandardFuel.cpp.i:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/StandardFuel.cpp.i
.PHONY : src/StandardFuel.cpp.i

src/StandardFuel.s: src/StandardFuel.cpp.s

.PHONY : src/StandardFuel.s

# target to generate assembly for a file
src/StandardFuel.cpp.s:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/StandardFuel.cpp.s
.PHONY : src/StandardFuel.cpp.s

src/StartPoint.o: src/StartPoint.cpp.o

.PHONY : src/StartPoint.o

# target to build an object file
src/StartPoint.cpp.o:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/StartPoint.cpp.o
.PHONY : src/StartPoint.cpp.o

src/StartPoint.i: src/StartPoint.cpp.i

.PHONY : src/StartPoint.i

# target to preprocess a source file
src/StartPoint.cpp.i:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/StartPoint.cpp.i
.PHONY : src/StartPoint.cpp.i

src/StartPoint.s: src/StartPoint.cpp.s

.PHONY : src/StartPoint.s

# target to generate assembly for a file
src/StartPoint.cpp.s:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/StartPoint.cpp.s
.PHONY : src/StartPoint.cpp.s

src/Startup.o: src/Startup.cpp.o

.PHONY : src/Startup.o

# target to build an object file
src/Startup.cpp.o:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Startup.cpp.o
.PHONY : src/Startup.cpp.o

src/Startup.i: src/Startup.cpp.i

.PHONY : src/Startup.i

# target to preprocess a source file
src/Startup.cpp.i:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Startup.cpp.i
.PHONY : src/Startup.cpp.i

src/Startup.s: src/Startup.cpp.s

.PHONY : src/Startup.s

# target to generate assembly for a file
src/Startup.cpp.s:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Startup.cpp.s
.PHONY : src/Startup.cpp.s

src/Test.o: src/Test.cpp.o

.PHONY : src/Test.o

# target to build an object file
src/Test.cpp.o:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Test.cpp.o
.PHONY : src/Test.cpp.o

src/Test.i: src/Test.cpp.i

.PHONY : src/Test.i

# target to preprocess a source file
src/Test.cpp.i:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Test.cpp.i
.PHONY : src/Test.cpp.i

src/Test.s: src/Test.cpp.s

.PHONY : src/Test.s

# target to generate assembly for a file
src/Test.cpp.s:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Test.cpp.s
.PHONY : src/Test.cpp.s

src/TimeUtil.o: src/TimeUtil.cpp.o

.PHONY : src/TimeUtil.o

# target to build an object file
src/TimeUtil.cpp.o:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/TimeUtil.cpp.o
.PHONY : src/TimeUtil.cpp.o

src/TimeUtil.i: src/TimeUtil.cpp.i

.PHONY : src/TimeUtil.i

# target to preprocess a source file
src/TimeUtil.cpp.i:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/TimeUtil.cpp.i
.PHONY : src/TimeUtil.cpp.i

src/TimeUtil.s: src/TimeUtil.cpp.s

.PHONY : src/TimeUtil.s

# target to generate assembly for a file
src/TimeUtil.cpp.s:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/TimeUtil.cpp.s
.PHONY : src/TimeUtil.cpp.s

src/Trim.o: src/Trim.cpp.o

.PHONY : src/Trim.o

# target to build an object file
src/Trim.cpp.o:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Trim.cpp.o
.PHONY : src/Trim.cpp.o

src/Trim.i: src/Trim.cpp.i

.PHONY : src/Trim.i

# target to preprocess a source file
src/Trim.cpp.i:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Trim.cpp.i
.PHONY : src/Trim.cpp.i

src/Trim.s: src/Trim.cpp.s

.PHONY : src/Trim.s

# target to generate assembly for a file
src/Trim.cpp.s:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Trim.cpp.s
.PHONY : src/Trim.cpp.s

src/UTM.o: src/UTM.cpp.o

.PHONY : src/UTM.o

# target to build an object file
src/UTM.cpp.o:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/UTM.cpp.o
.PHONY : src/UTM.cpp.o

src/UTM.i: src/UTM.cpp.i

.PHONY : src/UTM.i

# target to preprocess a source file
src/UTM.cpp.i:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/UTM.cpp.i
.PHONY : src/UTM.cpp.i

src/UTM.s: src/UTM.cpp.s

.PHONY : src/UTM.s

# target to generate assembly for a file
src/UTM.cpp.s:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/UTM.cpp.s
.PHONY : src/UTM.cpp.s

src/Util.o: src/Util.cpp.o

.PHONY : src/Util.o

# target to build an object file
src/Util.cpp.o:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Util.cpp.o
.PHONY : src/Util.cpp.o

src/Util.i: src/Util.cpp.i

.PHONY : src/Util.i

# target to preprocess a source file
src/Util.cpp.i:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Util.cpp.i
.PHONY : src/Util.cpp.i

src/Util.s: src/Util.cpp.s

.PHONY : src/Util.s

# target to generate assembly for a file
src/Util.cpp.s:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Util.cpp.s
.PHONY : src/Util.cpp.s

src/Weather.o: src/Weather.cpp.o

.PHONY : src/Weather.o

# target to build an object file
src/Weather.cpp.o:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Weather.cpp.o
.PHONY : src/Weather.cpp.o

src/Weather.i: src/Weather.cpp.i

.PHONY : src/Weather.i

# target to preprocess a source file
src/Weather.cpp.i:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Weather.cpp.i
.PHONY : src/Weather.cpp.i

src/Weather.s: src/Weather.cpp.s

.PHONY : src/Weather.s

# target to generate assembly for a file
src/Weather.cpp.s:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/Weather.cpp.s
.PHONY : src/Weather.cpp.s

src/WeatherModel.o: src/WeatherModel.cpp.o

.PHONY : src/WeatherModel.o

# target to build an object file
src/WeatherModel.cpp.o:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/WeatherModel.cpp.o
.PHONY : src/WeatherModel.cpp.o

src/WeatherModel.i: src/WeatherModel.cpp.i

.PHONY : src/WeatherModel.i

# target to preprocess a source file
src/WeatherModel.cpp.i:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/WeatherModel.cpp.i
.PHONY : src/WeatherModel.cpp.i

src/WeatherModel.s: src/WeatherModel.cpp.s

.PHONY : src/WeatherModel.s

# target to generate assembly for a file
src/WeatherModel.cpp.s:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/WeatherModel.cpp.s
.PHONY : src/WeatherModel.cpp.s

src/WxShield.o: src/WxShield.cpp.o

.PHONY : src/WxShield.o

# target to build an object file
src/WxShield.cpp.o:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/WxShield.cpp.o
.PHONY : src/WxShield.cpp.o

src/WxShield.i: src/WxShield.cpp.i

.PHONY : src/WxShield.i

# target to preprocess a source file
src/WxShield.cpp.i:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/WxShield.cpp.i
.PHONY : src/WxShield.cpp.i

src/WxShield.s: src/WxShield.cpp.s

.PHONY : src/WxShield.s

# target to generate assembly for a file
src/WxShield.cpp.s:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/WxShield.cpp.s
.PHONY : src/WxShield.cpp.s

src/stdafx.o: src/stdafx.cpp.o

.PHONY : src/stdafx.o

# target to build an object file
src/stdafx.cpp.o:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/stdafx.cpp.o
.PHONY : src/stdafx.cpp.o

src/stdafx.i: src/stdafx.cpp.i

.PHONY : src/stdafx.i

# target to preprocess a source file
src/stdafx.cpp.i:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/stdafx.cpp.i
.PHONY : src/stdafx.cpp.i

src/stdafx.s: src/stdafx.cpp.s

.PHONY : src/stdafx.s

# target to generate assembly for a file
src/stdafx.cpp.s:
	$(MAKE) -f CMakeFiles/FireSTARR.dir/build.make CMakeFiles/FireSTARR.dir/src/stdafx.cpp.s
.PHONY : src/stdafx.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... FireSTARR"
	@echo "... src/Database.o"
	@echo "... src/Database.i"
	@echo "... src/Database.s"
	@echo "... src/Duff.o"
	@echo "... src/Duff.i"
	@echo "... src/Duff.s"
	@echo "... src/Environment.o"
	@echo "... src/Environment.i"
	@echo "... src/Environment.s"
	@echo "... src/EnvironmentInfo.o"
	@echo "... src/EnvironmentInfo.i"
	@echo "... src/EnvironmentInfo.s"
	@echo "... src/FBP45.o"
	@echo "... src/FBP45.i"
	@echo "... src/FBP45.s"
	@echo "... src/FWI.o"
	@echo "... src/FWI.i"
	@echo "... src/FWI.s"
	@echo "... src/FireSpread.o"
	@echo "... src/FireSpread.i"
	@echo "... src/FireSpread.s"
	@echo "... src/FireWeather.o"
	@echo "... src/FireWeather.i"
	@echo "... src/FireWeather.s"
	@echo "... src/FuelLookup.o"
	@echo "... src/FuelLookup.i"
	@echo "... src/FuelLookup.s"
	@echo "... src/FuelType.o"
	@echo "... src/FuelType.i"
	@echo "... src/FuelType.s"
	@echo "... src/FwiStream.o"
	@echo "... src/FwiStream.i"
	@echo "... src/FwiStream.s"
	@echo "... src/Grid.o"
	@echo "... src/Grid.i"
	@echo "... src/Grid.s"
	@echo "... src/IntensityMap.o"
	@echo "... src/IntensityMap.i"
	@echo "... src/IntensityMap.s"
	@echo "... src/Iteration.o"
	@echo "... src/Iteration.i"
	@echo "... src/Iteration.s"
	@echo "... src/Log.o"
	@echo "... src/Log.i"
	@echo "... src/Log.s"
	@echo "... src/Main.o"
	@echo "... src/Main.i"
	@echo "... src/Main.s"
	@echo "... src/Model.o"
	@echo "... src/Model.i"
	@echo "... src/Model.s"
	@echo "... src/Observer.o"
	@echo "... src/Observer.i"
	@echo "... src/Observer.s"
	@echo "... src/Perimeter.o"
	@echo "... src/Perimeter.i"
	@echo "... src/Perimeter.s"
	@echo "... src/ProbabilityMap.o"
	@echo "... src/ProbabilityMap.i"
	@echo "... src/ProbabilityMap.s"
	@echo "... src/SafeVector.o"
	@echo "... src/SafeVector.i"
	@echo "... src/SafeVector.s"
	@echo "... src/Scenario.o"
	@echo "... src/Scenario.i"
	@echo "... src/Scenario.s"
	@echo "... src/Settings.o"
	@echo "... src/Settings.i"
	@echo "... src/Settings.s"
	@echo "... src/StandardFuel.o"
	@echo "... src/StandardFuel.i"
	@echo "... src/StandardFuel.s"
	@echo "... src/StartPoint.o"
	@echo "... src/StartPoint.i"
	@echo "... src/StartPoint.s"
	@echo "... src/Startup.o"
	@echo "... src/Startup.i"
	@echo "... src/Startup.s"
	@echo "... src/Test.o"
	@echo "... src/Test.i"
	@echo "... src/Test.s"
	@echo "... src/TimeUtil.o"
	@echo "... src/TimeUtil.i"
	@echo "... src/TimeUtil.s"
	@echo "... src/Trim.o"
	@echo "... src/Trim.i"
	@echo "... src/Trim.s"
	@echo "... src/UTM.o"
	@echo "... src/UTM.i"
	@echo "... src/UTM.s"
	@echo "... src/Util.o"
	@echo "... src/Util.i"
	@echo "... src/Util.s"
	@echo "... src/Weather.o"
	@echo "... src/Weather.i"
	@echo "... src/Weather.s"
	@echo "... src/WeatherModel.o"
	@echo "... src/WeatherModel.i"
	@echo "... src/WeatherModel.s"
	@echo "... src/WxShield.o"
	@echo "... src/WxShield.i"
	@echo "... src/WxShield.s"
	@echo "... src/stdafx.o"
	@echo "... src/stdafx.i"
	@echo "... src/stdafx.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

