# syntax=docker/dockerfile:1
FROM thinkwhere/gdal-python:3.6
WORKDIR /appl
COPY .docker/requirements_gis.txt requirements_gis.txt
WORKDIR /appl/GIS/
RUN python -m pip install --upgrade pip \
	&& pip uninstall -y gdal \
  && pip install -r /appl/requirements_gis.txt \
  && pip install "gdal==`gdal-config --version`" \
  && rm -rf \
      /usr/share/man/* \
      /usr/includes/* \
      /var/cache/apk/* \
      /root/.npm/* \
      /usr/lib/node_modules/npm/man/* \
      /usr/lib/node_modules/npm/doc/* \
      /usr/lib/node_modules/npm/html/* \
      /usr/lib/node_modules/npm/scripts/*
