FROM php:7.2-apache
WORKDIR /var/www/html/wxshield/
RUN apt-get update \
	&& apt-get install -y libpq-dev \
	&& docker-php-ext-configure pgsql -with-pgsql=/usr/local/pgsql \
	&& docker-php-ext-install pdo pdo_pgsql pgsql \
	&& apt-get install -y wget unzip \
	&& wget --no-check-certificate https://github.com/twbs/bootstrap/releases/download/v3.4.1/bootstrap-3.4.1-dist.zip \
	&& rm -rf bootstrap \
	&& unzip -o bootstrap-3.4.1-dist.zip \
	&& rm bootstrap-3.4.1-dist.zip \
	&& mv bootstrap-3.4.1-dist bootstrap \
	&& mkdir -p /var/www/html/wxshield/js/ \
	&& cd /var/www/html/wxshield/js/ \
	&& wget --no-check-certificate https://code.jquery.com/jquery-1.11.3.js \
	&& wget --no-check-certificate https://code.jquery.com/jquery-1.11.3.min.js \
	&& wget --no-check-certificate https://github.com/jquery-validation/jquery-validation/archive/1.11.1.zip \
	&& unzip -o 1.11.1.zip \
	&& rm 1.11.1.zip \
	&& mv jquery-validation-1.11.1/jquery.validate.js ./ \
	&& rm -rf jquery-validation-1.11.1 \
	&& wget --no-check-certificate https://github.com/MrRio/jsPDF/archive/v1.2.61.zip \
	&& unzip -o v1.2.61.zip \
	&& rm v1.2.61.zip \
	&& mkdir -p /var/www/html/wxshield/js/jspdf \
	&& mv /var/www/html/wxshield/js/jsPDF-1.2.61/dist/jspdf.min.js /var/www/html/wxshield/js/jspdf/jspdf.js \
	&& rm -rf jsPDF-1.2.61 \
	&& apt-get clean && rm -rf /var/lib/apt/lists/* \
	&& rm -rf \
      /usr/share/man/* \
      /usr/includes/* \
      /var/cache/apk/* \
      /root/.npm/* \
      /usr/lib/node_modules/npm/man/* \
      /usr/lib/node_modules/npm/doc/* \
      /usr/lib/node_modules/npm/html/* \
      /usr/lib/node_modules/npm/scripts/*
COPY WeatherSHIELD/gui/ /var/www/html/wxshield/
